spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl?characterEncoding=utf-8&useSSL=false
    username: root
    password:
  jpa:
    database: MYSQL
    # 打印sql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false



